### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by piacentini**
Hi. I was testing your class and found two minor issues, please see the attached merge request. One has been reported before and it is harmless as the current timestamp returned by a date object already converts to a 8 digit HEX string. But as you are checking anyway, it is nice to use the correct mask size (8 characters).
The second is an off by one comparison. I simply change the location of the increment, alternatively you could also use a >= when comparing the upper limit of the increment value.
BTW I have a PHP version of this class if you are interested, not sure if it is ok to post it here or not.

### CODE REVIEW

**Comment by zippy1981** [comment]
Didn't see this until just now. I am adding unit tests to ObjectId.js and I will create merge all the pull requests. Out of curosity, are you using this on any public websites and would you be interested in loading this from a CDN?

**Comment by zippy1981** [comment]
Awesome, merged. BTW I have unit tests now.

**Comment by piacentini** [comment]
I am actually not using it right now as my project needed an implementation in php. I know I could install and use the Mongo driver, but this is overkill for my specific needs (as I am using Mongo-like ids but not Mongo itself). So I made a PHP version heavily inspired by it. You can see it at https://github.com/piacentini/ObjectId.php

**Comment by zippy1981** [comment]
That's pretty awesome.

**Pull request merged**
